module:cluster:
- erasplit/cluster/**/*

module:common:
- erasplit/common/**/*

module:compose:
- erasplit/compose/**/*

module:covariance:
- erasplit/covariance/**/*

module:cross_decomposition:
- erasplit/cross_decomposition/**/*

module:datasets:
- erasplit/datasets/**/*

module:decomposition:
- erasplit/decomposition/**/*

module:ensemble:
- erasplit/ensemble/**/*

module:feature_extraction:
- erasplit/feature_extraction/**/*

module:feature_selection:
- erasplit/feature_selection/**/*

module:gaussian_process:
- erasplit/gaussian_process/**/*

module:impute:
- erasplit/impute/**/*

module:inspection:
- erasplit/inspection/**/*

module:linear_model:
- erasplit/linear_model/**/*

module:manifold:
- erasplit/manifold/**/*

module:metrics:
- erasplit/metrics/**/*

module:mixture:
- erasplit/mixture/**/*

module:model_selection:
- erasplit/model_selection/**/*

module:naive_bayes:
- erasplit/naive_bayes.py

module:neighbors:
- erasplit/neighbors/**/*

module:neural_network:
- erasplit/neural_network/**/*

module:pipeline:
- erasplit/pipeline.py

module:preprocessing:
- erasplit/preprocessing/**/*

module:semi_supervised:
- erasplit/semi_supervised/**/*

module:svm:
- erasplit/svm/**/*

module:tree:
- erasplit/tree/**/*

module:utils:
- erasplit/utils/**/*
