[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
    "Cython>=0.29.33,<=3.0.12",
    "numpy>=1.17.3,<2.0.0",  # Range for NumPy
    "scipy>=1.3.2",
]