name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel numpy scipy cython

      - name: Build wheels with cibuildwheel
        run: |
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PLATFORM: ${{ matrix.os == 'macos-latest' && 'macos' || matrix.os }}  # Set macos for macOS
          CIBW_ARCHS: ${{ matrix.os == 'macos-latest' && 'arm64,x86_64' || 'auto' }}  # Enable both architectures on macOS
          CIBW_BUILD: cp${{ matrix.python-version }}*

      - name: Upload to PyPI
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
